/*
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT!
 *
 * generated by gattdbgen from depend_Release_CSR100x/app_gatt_db.db_
 */

#include "depend_Release_CSR100x/app_gatt_db.h"

/* GATT database */
uint16 gattDatabase[] = {
    /* 0001: Primary Service 1800 */
    0x0002, 0x0018,
    /* 0002: Characteristic Declaration 2a00 */
    0x3005, 0x0203, 0x0000, 0x2a00,
    /* 0003: YUE Metronome */
    0xd00d, 0x5955, 0x4520, 0x4d65, 0x7472, 0x6f6e, 0x6f6d, 0x6500,
    /* 0004: Characteristic Declaration 2a01 */
    0x3005, 0x0205, 0x0001, 0x2a00,
    /* 0005: .. */
    0xd002, 0x0002,
    /* 0006: Characteristic Declaration 2a04 */
    0x3005, 0x0207, 0x0004, 0x2a00,
    /* 0007: ......d. */
    0xd008, 0x1400, 0x1400, 0x0800, 0x6400,
    /* 0008: Primary Service 2200 */
    0x0002, 0x0022,
    /* 0009: Characteristic Declaration 2201 */
    0x3005, 0x080a, 0x0001, 0x2200,
    /* 000a: . */
    0xd401, 0x0000,
    /* 000b: Characteristic Declaration 2202 */
    0x3005, 0x080c, 0x0002, 0x2200,
    /* 000c: .... */
    0xd404, 0x0000, 0x0000,
    /* 000d: Characteristic Declaration 2203 */
    0x3005, 0x080e, 0x0003, 0x2200,
    /* 000e: .... */
    0xd404, 0x0000, 0x0000,
    /* 000f: Characteristic Declaration 2204 */
    0x3005, 0x0810, 0x0004, 0x2200,
    /* 0010: ................ */
    0xd410, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
    /* 0011: Characteristic Declaration 2205 */
    0x3005, 0x0812, 0x0005, 0x2200,
    /* 0012: . */
    0xd401, 0x0000,
    /* 0013: Characteristic Declaration 2206 */
    0x3005, 0x0214, 0x0006, 0x2200,
    /* 0014: . */
    0xd401, 0x0000,
    /* 0015: Characteristic Declaration 2211 */
    0x3005, 0x0216, 0x0011, 0x2200,
    /* 0016: . */
    0xd401, 0x0000,
    /* 0017: Primary Service 1801 */
    0x0002, 0x0118,
};

uint16 *GattGetDatabase(uint16 *len)
{
    *len = sizeof(gattDatabase);
    return gattDatabase;
}

/* End-of-File */
